"""initial migration

Revision ID: 3897143e72eb
Revises: 904ebc2943f7
Create Date: 2025-04-18 15:08:05.482472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3897143e72eb'
down_revision: Union[str, None] = '904ebc2943f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('description', sa.String(), nullable=True))
    op.create_index(op.f('ix_Products_description'), 'Products', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Products_description'), table_name='Products')
    op.drop_column('Products', 'description')
    # ### end Alembic commands ###
