"""initial migration

Revision ID: 813ca3b70384
Revises: 3897143e72eb
Create Date: 2025-04-18 15:34:28.186951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813ca3b70384'
down_revision: Union[str, None] = '3897143e72eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Products_description', table_name='Products')
    op.drop_column('Products', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_Products_description', 'Products', ['description'], unique=False)
    # ### end Alembic commands ###
